### ISSUE TITLE
Bookmarklet not working...

### ISSUE THREAD

**Issue by bugsysop** [nunux-keeper/keeper-web-app#21]
Tried with Chromium and Vivaldi Browser on GNU/Linux (Ubuntu LTS): nothing happens

**Comment by ncarlier** [comment]
Thanks for the report. I will test that. (only tested with Chrome and Firefox)

**Comment by bugsysop** [comment]
Tested with Firefox, work as a charm...

**Comment by ncarlier** [comment]
Hi, I just pushed a fix about the bookmaklet. The base URL was not correctly calculated. 

Unfortunately last version of chromium introduced a bug related to drag and drop over iframe:  https://bugs.chromium.org/p/chromium/issues/detail?id=908815

This bug impact the bookmarklet behavior. Drag and drop is no longer working on any chromium based browser :(

You can use this codepen to see if your browser is affected: https://codepen.io/jgalama/pen/EOexMo?editors=1111

Waiting for a chromium fix...

**Comment by ncarlier** [comment]
Issue on Chrome fixed.
