### ISSUE TITLE
project still alive - app.nunuxkeeper.org no DNS

### ISSUE THREAD

**Issue by fundef1** [nunux-keeper/keeper-web-app#33]
Hi, 
not sure where to post this - but this is the most recently updated repo.

**is NUNUX still actively maintained/developed?**

I wanted to try the hosted version via https://app.nunux.org/keeper , **but DNS doesn't resolve**.
nunux-keeper is an archive but 'new project' points to all repo's
Dockerhub image was last updated 4 years ago

if not active, could you point me to some alternatives ?
thanks!

**Comment by ncarlier** [comment]
Hi, Nunux Keeper no more maintained. You can use [readflow.app](https://github.com/ncarlier/readflow) as an alternative. It's a kind of overhaul of Nunux Keeper.

**Comment by fundef1** [comment]
Thanks @ncarlier for the quick response.
I'll have a look at readflow!
